"""
graph_client.py — Gmail API client.

Replaces the Microsoft Graph API client.
Uses Google OAuth credentials from token_google.json (generated by auth.py).

Same interface as the original graph_client.py so nothing else in the
agent needs to change — main.py, alerter.py, router.py etc. are unaffected.
"""
from __future__ import annotations

import base64
import email as email_lib
import logging
import os
import re
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Optional

log = logging.getLogger("graph_client")

TOKEN_FILE = Path(__file__).parent / "token_google.json"
CREDS_FILE = Path(__file__).parent / "google_credentials.json"

SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.modify",
]

INBOUND_LABEL = "Agent Processed"


class GraphClient:
    """
    Gmail API client with the same interface as the original Microsoft
    Graph client. Drop-in replacement — no changes needed in main.py.
    """

    def __init__(self) -> None:
        self._sender = os.environ.get("SENDER_EMAIL", "")
        self._service = self._build_service()

    def _build_service(self):
        try:
            from googleapiclient.discovery import build
            from google.oauth2.credentials import Credentials
            from google.auth.transport.requests import Request
        except ImportError:
            raise ImportError(
                "Google libraries not installed. Run:\n"
                "pip install google-auth google-auth-oauthlib "
                "google-auth-httplib2 google-api-python-client"
            )

        # Bootstrap token from env var (Railway doesn't persist files)
        token_json = os.environ.get("TOKEN_GOOGLE_JSON")
        if token_json:
            TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
            TOKEN_FILE.write_text(token_json, encoding="utf-8")

        if not TOKEN_FILE.exists():
            raise FileNotFoundError(
                f"token_google.json not found at {TOKEN_FILE}. "
                "Run 'python auth.py' first."
            )

        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)

        # Refresh if expired
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
            TOKEN_FILE.write_text(creds.to_json())
            # Update env var with refreshed token for Railway
            log.info("Gmail token refreshed.")

        return build("gmail", "v1", credentials=creds)

    # ── Connection test ────────────────────────────────────────────────────

    def test_connection(self) -> None:
        profile = self._service.users().getProfile(userId="me").execute()
        email   = profile.get("emailAddress", "unknown")
        log.info(f"Gmail API connected as {email}")

    # ── Inbox polling ──────────────────────────────────────────────────────

    def get_new_replies(self) -> list[dict]:
        """
        Returns all unread messages in the inbox.
        alerter.py decides which ones are replies vs. new inbounds.
        """
        try:
            result = self._service.users().messages().list(
                userId="me",
                labelIds=["INBOX", "UNREAD"],
                maxResults=50,
            ).execute()
        except Exception as e:
            log.error(f"Gmail list error: {e}")
            return []

        messages = result.get("messages", [])
        if not messages:
            return []

        replies = []
        for msg_stub in messages:
            try:
                msg = self._service.users().messages().get(
                    userId="me",
                    id=msg_stub["id"],
                    format="full",
                ).execute()
                parsed = self._parse_message(msg)
                if parsed:
                    replies.append(parsed)
            except Exception as e:
                log.warning(f"Failed to fetch message {msg_stub['id']}: {e}")

        log.info(f"Fetched {len(replies)} unread messages from Gmail")
        return replies

    def _parse_message(self, msg: dict) -> Optional[dict]:
        headers = {
            h["name"].lower(): h["value"]
            for h in msg.get("payload", {}).get("headers", [])
        }
        subject    = headers.get("subject", "")
        from_raw   = headers.get("from", "")
        from_email = _extract_email(from_raw)
        from_name  = _extract_name(from_raw)

        # Get body
        body = _extract_body(msg.get("payload", {}))

        return {
            "message_id":  msg["id"],
            "thread_id":   msg.get("threadId", ""),
            "from_email":  from_email.lower(),
            "from_name":   from_name,
            "subject":     subject,
            "body":        body,
            "thread_body": body,
            "received_at": headers.get("date", ""),
        }

    # ── Sending ────────────────────────────────────────────────────────────

    def send_email(
        self,
        to: str,
        subject: str,
        body: str,
        html: Optional[str] = None,
        cc: Optional[list[str]] = None,
        reply_to_message_id: Optional[str] = None,
        tracking_token: Optional[str] = None,
    ) -> None:
        """Sends an email from Pawel's Gmail account."""
        # Inject tracking pixel into HTML emails
        if html and tracking_token:
            pixel_url = (
                f"{_get_base_url()}/track/open/{tracking_token}"
                f"?e={_url_encode(to)}&c={_url_encode(tracking_token)}"
            )
            pixel = f'<img src="{pixel_url}" width="1" height="1" alt="" style="display:none;"/>'
            # Insert before closing body tag, or append if no body tag
            if "</body>" in html:
                html = html.replace("</body>", f"{pixel}</body>")
            else:
                html = html + pixel
        if html:
            mime_msg = MIMEMultipart("alternative")
            mime_msg.attach(MIMEText(body, "plain"))
            mime_msg.attach(MIMEText(html, "html"))
        elif tracking_token:
            # Plain text email — wrap in minimal HTML to enable tracking pixel
            pixel_url = (
                f"{_get_base_url()}/track/open/{tracking_token}"
                f"?e={_url_encode(to)}&c={_url_encode(tracking_token)}"
            )
            pixel = f'<img src="{pixel_url}" width="1" height="1" alt="" style="display:none;"/>'
            html_body = f"<html><body><pre style='font-family:Arial,sans-serif;font-size:14px;white-space:pre-wrap'>{body}</pre>{pixel}</body></html>"
            mime_msg = MIMEMultipart("alternative")
            mime_msg.attach(MIMEText(body, "plain"))
            mime_msg.attach(MIMEText(html_body, "html"))
        else:
            mime_msg = MIMEText(body, "plain")

        mime_msg["to"]      = to
        mime_msg["from"]    = self._sender
        mime_msg["subject"] = subject
        if cc:
            mime_msg["cc"] = ", ".join(cc)

        raw = base64.urlsafe_b64encode(mime_msg.as_bytes()).decode()
        payload: dict = {"raw": raw}

        # Reply in thread if message ID provided
        if reply_to_message_id:
            # Get the thread ID from the original message
            try:
                orig = self._service.users().messages().get(
                    userId="me", id=reply_to_message_id, format="metadata"
                ).execute()
                payload["threadId"] = orig.get("threadId", "")
            except Exception:
                pass

        self._service.users().messages().send(
            userId="me", body=payload
        ).execute()
        log.info(f"Gmail sent to {to} — {subject!r}")

    # ── Message management ─────────────────────────────────────────────────

    def mark_as_read(self, message_id: str) -> None:
        try:
            self._service.users().messages().modify(
                userId="me",
                id=message_id,
                body={"removeLabelIds": ["UNREAD"]},
            ).execute()
        except Exception as e:
            log.warning(f"Could not mark {message_id} as read: {e}")

    def move_to_processed(self, message_id: str) -> None:
        """Adds an 'Agent Processed' label to the message."""
        try:
            label_id = self._get_or_create_label(INBOUND_LABEL)
            self._service.users().messages().modify(
                userId="me",
                id=message_id,
                body={"addLabelIds": [label_id], "removeLabelIds": ["INBOX"]},
            ).execute()
        except Exception as e:
            log.warning(f"Could not move {message_id}: {e}")

    def _get_or_create_label(self, name: str) -> str:
        """Returns the ID of a Gmail label, creating it if needed."""
        labels = self._service.users().labels().list(userId="me").execute()
        for label in labels.get("labels", []):
            if label["name"] == name:
                return label["id"]
        # Create it
        new_label = self._service.users().labels().create(
            userId="me", body={"name": name}
        ).execute()
        log.info(f"Created Gmail label: {name}")
        return new_label["id"]


# ── Helpers ────────────────────────────────────────────────────────────────

def _extract_email(from_header: str) -> str:
    """Extracts email from 'Name <email@domain.com>' or 'email@domain.com'."""
    match = re.search(r"<([^>]+)>", from_header)
    if match:
        return match.group(1).strip()
    return from_header.strip()


def _extract_name(from_header: str) -> str:
    """Extracts display name from 'Name <email>' format."""
    match = re.match(r'^"?([^"<]+)"?\s*<', from_header)
    if match:
        return match.group(1).strip()
    return _extract_email(from_header)


def _extract_body(payload: dict) -> str:
    """Recursively extracts plain text body from a Gmail message payload."""
    mime_type = payload.get("mimeType", "")
    body_data = payload.get("body", {}).get("data", "")

    if body_data:
        decoded = base64.urlsafe_b64decode(body_data + "==").decode("utf-8", errors="replace")
        if "text/plain" in mime_type:
            return decoded.strip()
        if "text/html" in mime_type:
            return _strip_html(decoded).strip()

    # Recurse into multipart
    for part in payload.get("parts", []):
        result = _extract_body(part)
        if result:
            return result

    return ""


def _get_base_url() -> str:
    """Returns the Railway app base URL for tracking pixel."""
    return os.environ.get(
        "APP_BASE_URL",
        "https://can-usa-outbound-production.up.railway.app"
    )


def _url_encode(s: str) -> str:
    """Simple URL encoding for query params."""
    import urllib.parse
    return urllib.parse.quote(s, safe="")


def _strip_html(html: str) -> str:
    for tag in ["</p>", "</div>", "<br>", "<br/>", "<br />"]:
        html = html.replace(tag, "\n")
    plain = re.sub(r"<[^>]+>", "", html)
    plain = (
        plain
        .replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
        .replace("&nbsp;", " ").replace("&quot;", '"').replace("&#39;", "'")
    )
    return re.sub(r"\n{3,}", "\n\n", plain).strip()